name: Inventory CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --------------------------
  # 1. CI: запуск тестов
  # --------------------------
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest -vv

  # --------------------------
  # 2. CD: build + deploy (локальный runner)
  # --------------------------
  deploy:
    needs: tests
    runs-on: self-hosted   # <-- важно: локальный runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build API image
        run: |
          docker build -t inventory-api:latest .

      - name: Build Frontend image
        run: |
          for ($i = 1; $i -le 5; $i++) {
            Write-Host "Attempt $i to build frontend..."
            docker build -t inventory-frontend:latest ./frontend
            if ($LASTEXITCODE -eq 0) {
              Write-Host "Frontend build succeeded."
              break
            }
            Write-Host "Build failed. Retrying in 5 seconds..."
            Start-Sleep -Seconds 5
          }

          if ($LASTEXITCODE -ne 0) {
            throw "Failed to build image after 5 attempts"
          }
      

      - name: Update API service in Swarm
        run: |
          docker service update --force \
            --image inventory-api:latest \
            inventory_inventory-api

      - name: Update Frontend service in Swarm
        run: |
          docker service update --force \
            --image inventory-frontend:latest \
            inventory_frontend

      - name: Show service list (debug)
        run: docker service ls
